books_app/routes.py
"""Import packages and modules."""
import os
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from books_app.models import Book, Author, Genre, User
from books_app.forms import BookForm, AuthorForm, GenreForm

# Import app and db from events_app package so that we can run app
from books_app import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################


@main.route("/")
def homepage():
    all_books = Book.query.all()
    all_users = User.query.all()
    return render_template("home.html", all_books=all_books, all_users=all_users)


@main.route("/create_book", methods=["GET", "POST"])
def create_book():
    form = BookForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        new_book = Book(
            title=form.title.data,
            publish_date=form.publish_date.data,
            author=form.author.data,
            audience=form.audience.data,
            genres=form.genres.data,
        )
        db.session.add(new_book)
        db.session.commit()

        flash("New book was created successfully.")
        return redirect(url_for("main.book_detail", book_id=new_book.id))
    return render_template("create_book.html", form=form)


@main.route("/create_author", methods=["GET", "POST"])
def create_author():
    # TODO: Make an AuthorForm instance
    form = AuthorForm()
    # TODO: If the form was submitted and is valid, create a new Author object
    # and save to the database, then flash a success message to the user and
    # redirect to the homepage
    if form.validate_on_submit():
        new_author = Author(
            name=form.author.data,
            biography=form.biography.data,
        )
        db.session.add(new_author)
        db.session.commit()

        flash("New author was created successfully.")
        # TODO: Send the form object to the template, and use it to render the form
        # fields
        return redirect(url_for("main.homepage"))
    return render_template("create_author.html", form=form)


@main.route("/create_genre", methods=["GET", "POST"])
def create_genre():
    # TODO: Make a GenreForm instance
    form = GenreForm()
    # TODO: If the form was submitted and is valid, create a new Genre object
    # and save to the database, then flash a success message to the user and
    # redirect to the homepage
    if form.validate_on_submit():
        new_genre = Genre(name=form.genre.data)
        db.session.add(new_genre)
        db.session.commit()

        flash("New genre was created successfully.")
        # TODO: Send the form object to the template, and use it to render the form
        # fields
        return redirect(url_for("main.homepage"))
    return render_template("create_genre.html", form=form)


@main.route("/create_user", methods=["GET", "POST"])
def create_user():
    # STRETCH CHALLENGE: Fill out the Create User route
    return "Not Yet Implemented"


@main.route("/book/<book_id>", methods=["GET", "POST"])
def book_detail(book_id):
    book = Book.query.get(book_id)
    form = BookForm(obj=book)

    # TODO: If the form was submitted and is valid, update the fields in the
    # Book object and save to the database, then flash a success message to the
    # user and redirect to the book detail page
    if form.validate_on_submit():
        book.title = (form.title.data,)
        book.publish_date = (form.publish_data.data,)
        book.author = (form.author.data,)
        book.audience = (form.audience.data,)
        book.genres = form.genres.data
    db.session.add(book)
    db.session.commit()

    flash("Book was successfully updated.")
    return render_template("book_detail.html", book=book, form=form)


@main.route("/profile/<username>")
def profile(username):
    # TODO: Make a query for the user with the given username, and send to the
    # template
    user = User.query.get(username)

    # STRETCH CHALLENGE: Add ability to modify a user's username or favorite
    # books
    context = {user: "user"}
    return render_template("profile.html", username=username, **context)

books_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Books Site</title>
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
        <div id="content">
            <a href="/">Home</a>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

books_app/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ book.title }}</h1>

<p>
    <strong>Author</strong>: {{ book.author.name }}
</p>

<p>
    <strong>Author Bio</strong>: {{ book.author.biography }}
</p>

<p>
    <strong>Publish date</strong>: {{ book.publish_date }}
</p>

<p>
    <strong>Audience</strong>: {{ book.audience }}
</p>

<p>
    <strong>Genres</strong>: 
    
    {% for genre in book.genres %}
    {{ genre.name }},
    {% endfor %}
</p>

<form method="POST" action="{{ url_for('main.book_detail', book_id=book.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Edit this book</legend>

        {{ form.title.label }}
        {{ form.title }}
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        
        {{ form.author.label }}
        {{ form.author }}
        
        {{ form.audience.label }}
        {{ form.audience }}
        
        {{ form.genres.label }}
        {{ form.genres }}
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/create_author.html
{% extends 'base.html' %}

{% block content %}

<p>Author creation form.</p>

<!-- TODO: Add a <form> element here and use the form variable to show the labels & fields -->
<form method="POST" action="{{ url_for('main.create_author') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a book</legend>

        {{ form.author.label }}
        {{ form.author }}

        {{ form.biography.label }}
        {{ form.biography }}

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/create_book.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_book') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a book</legend>

        {{ form.title.label }}
        {{ form.title }}

        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}

        {{ form.author.label }}
        {{ form.author }}

        {{ form.audience.label }}
        {{ form.audience }}

        {{ form.genres.label }}
        {{ form.genres }}

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/create_genre.html
{% extends 'base.html' %}

{% block content %}

<p>Genre creation form.</p>

<!-- TODO: Add a <form> element here and use the form variable to show the labels & fields -->
<form method="POST" action="{{ url_for('main.create_genre') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a genre</legend>

        {{ form.genre.label }}
        {{ form.genre }}

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h2>Books</h2>

<p>
    <a href="/create_book">+ New Book</a>
</p>

<p>
    <a href="/create_author">+ New Author</a>
</p>

<p>
    <a href="/create_genre">+ New Genre</a>
</p>

<ul>
{% for book in all_books %}
    <li><a href="/book/{{ book.id }}">{{ book.title }}</a> by {{ book.author.name }}</li>
{% endfor %}
</ul>

<h2>Users</h2>

<p>
    <a href="/create_user">+ New User</a>
</p>

<ul>
    {% for user in all_users %}
        <li><a href="/profile/{{ user.username }}">{{ user.username }}</a></li>
    {% endfor %}
</ul>



{% endblock %}

books_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<p>
Welcome to {{ username }}'s profile.
</p>

<!-- TODO: Display the user's actual favorites here -->

<p>
    {{ username }}'s favorite books are:

    <ul>
        <li>Your</li>
        <li>Favorites</li>
        <li>Go</li>
        <li>Here</li>
    </ul>
</p>

{% endblock %}